- address:
    x: 5
    y: 9
  side: b
  kind: k
- address:
    x: 8
    y: 8
  side: b
  kind: b
- address:
    x: 2
    y: 8
  side: b
  kind: r
- address:
    x: 4
    y: 9
  side: b
  kind: g
- address:
    x: 6
    y: 9
  side: b
  kind: g
- address:
    x: 3
    y: 9
  side: b
  kind: s
- address:
    x: 7
    y: 9
  side: b
  kind: s
- address:
    x: 2
    y: 9
  side: b
  kind: n
- address:
    x: 8
    y: 9
  side: b
  kind: n
- address:
    x: 1
    y: 9
  side: b
  kind: l
- address:
    x: 9
    y: 9
  side: b
  kind: l
- address:
    x: 1
    y: 7
  side: b
  kind: p
- address:
    x: 2
    y: 7
  side: b
  kind: p
- address:
    x: 3
    y: 7
  side: b
  kind: p
- address:
    x: 4
    y: 7
  side: b
  kind: p
- address:
    x: 5
    y: 7
  side: b
  kind: p
- address:
    x: 6
    y: 7
  side: b
  kind: p
- address:
    x: 7
    y: 7
  side: b
  kind: p
- address:
    x: 8
    y: 7
  side: b
  kind: p
- address:
    x: 9
    y: 7
  side: b
  kind: p
- address:
    x: 5
    y: 1
  side: w
  kind: k
- address:
    x: 8
    y: 2
  side: w
  kind: r
- address:
    x: 2
    y: 2
  side: w
  kind: b
- address:
    x: 4
    y: 1
  side: w
  kind: g
- address:
    x: 6
    y: 1
  side: w
  kind: g
- address:
    x: 3
    y: 1
  side: w
  kind: s
- address:
    x: 7
    y: 1
  side: w
  kind: s
- address:
    x: 2
    y: 1
  side: w
  kind: n
- address:
    x: 8
    y: 1
  side: w
  kind: n
- address:
    x: 1
    y: 1
  side: w
  kind: l
- address:
    x: 9
    y: 1
  side: w
  kind: l
- address:
    x: 1
    y: 3
  side: w
  kind: p
- address:
    x: 2
    y: 3
  side: w
  kind: p
- address:
    x: 3
    y: 3
  side: w
  kind: p
- address:
    x: 4
    y: 3
  side: w
  kind: p
- address:
    x: 5
    y: 3
  side: w
  kind: p
- address:
    x: 6
    y: 3
  side: w
  kind: p
- address:
    x: 7
    y: 3
  side: w
  kind: p
- address:
    x: 8
    y: 3
  side: w
  kind: p
- address:
    x: 9
    y: 3
  side: w
  kind: p
